backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "docs/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Contributor", name: "organisation", widget: "string"}
      - {label: "Authors", name: "author", widget: "string"}
      - {label: "Preview text", name: "preview", widget: "string"}
      - {label: "Badge", name: "badge", widget: "string"}
      - {label: "Tags", name: "tags", widget: "array", default: ["post"]}
      - {label: "Featured Image", name: "featureImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "media-links" 
    label: "Media links" 
    folder: "src/media-links" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Preview text", name: "preview", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
    