backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

site_url: https://auscmi.org/
display_url: https://auscmi.org

media_folder: "docs/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
<<<<<<< HEAD
    - name: "posts" # Used in routes, e.g., /admin/collections/posts
      label: "Posts" # Used in the UI
      folder: "src/posts" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{slug}}" # Filename template, e.g., title.md
      fields: # The fields for each document, usually in front matter
          - {
                label: "Title",
                name: "title",
                widget: "string",
                hint: "Try keep this less than 15-20 words. Use the same title as the underlying research article where possible.",
            }
          - {
                label: "Publish Date",
                name: "date",
                widget: "datetime",
                hint: "Date post published. If the post is for a journal article published in the past, use the date the journal article was published.",
            }
          - {
                label: "Contributor",
                name: "organisation",
                widget: "relation",
                collection: "contributors",
                value_field: "name",
                search_fields: ["name"],
                hint: "The name of the organisation contributing the article, e.g. Population Interventions Unit. This should match the organisation's specific tag, as detailed in website documentation.",
            }
          - {
                label: "Authors",
                name: "author",
                widget: "string",
                hint: "Authors of post, comma-separated. Format as 'title first-name last-name, e.g. Dr. John Doe, Dr. Jane Doe.",
            }
          - {
                label: "Preview text",
                name: "preview",
                widget: "string",
                hint: "1 or 2 sentences summarising the main idea, objective, or finding of the post. Use concise phrasing to catch reader's attention. Try to stay under 30-35 words.",
            }
          # - {label: "Badge", name: "badge", widget: "string", hint: "Controls the small, grey badge text that appears under post titles on the home-page. Usually the name of the contributor – i.e., same as 'contributor' field – but it can be something else."}
          - {
                label: "Tags",
                name: "tags",
                widget: "array",
                hint: "At a minimum, all posts must have a tag for their contributor. Please refer to the documentation before specifying a contributor tag, or copy over from a previous post by the same contributor. You can also specify other qualtiative tags depending on what the post is about, so that the post might be displayed on the relevant 'theme' page, e.g. Agent-based modelling, Melbourne, etc. (refer to website documentation for a full list of supported qualitative tags)",
            }
          - {
                label: "Featured Image",
                name: "featureImage",
                widget: "image",
                hint: "The image should be in high-resolution, its subject matter should be as generic as possible, and it should be royalty-free. Useful royalty-free sites: https://pixabay.com/, https://unsplash.com/.",
            }
          - {
                label: "Body",
                name: "body",
                widget: "markdown",
                hint: "Post content, using the 'objective', 'findings', 'conclusion' format specified in the website documentation.",
            }
    - name: "media-links"
      label: "Media links"
      folder: "src/media-links"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Preview text", name: "preview", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
    - name: "contributors"
      label: "Contributors"
      folder: "src/contributors"
      create: true
      slug: "{{slug}}"
      fields:
          - {
                label: "Name",
                name: "name",
                widget: "string",
                hint: "The name of the contributing organisation. The shorter the better.",
            }
          - {
                label: "Affiliation",
                name: "affiliation",
                required: false,
                widget: "string",
                hint: "University affiliation, where applicable. E.g. University of Melbourne.",
            }
          - {
                label: "Facebook",
                name: "facebook",
                required: false,
                widget: "string",
                hint: "Link to Facebook page (if they have one)",
            }
          - {
                label: "Twitter",
                name: "twitter",
                required: false,
                widget: "string",
                hint: "Link to Twitter (if they have one)",
            }
          - {
                label: "LinkedIn",
                name: "linkedin",
                required: false,
                widget: "string",
                hint: "Link to LinkedIn profile (if they have one)",
            }
          - {
                label: "Instagram",
                name: "instagram",
                required: false,
                widget: "string",
                hint: "Link to Instagram (if they have one)",
            }
          - {
                label: "Tag reference",
                name: "tagRef",
                widget: "string",
                hint: "The search-term used by the backend to match a post to its contributor. All posts by a given contributor should be tagged with that contributor's 'tag reference'.",
            }
          - {
                label: "Profile",
                name: "overview",
                widget: "markdown",
                hint: "A 50-100 word blurb about the contributing organisation, its research interests, and objectives.",
            }
    - name: "webinars"
      label: "Webinars"
      folder: "src/webinars"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "Publish Date",
                name: "date",
                widget: "datetime",
                "Date webinar presented.",
            }
          - {
                label: "Duration (minutes)",
                name: "duration",
                widget: "number",
                value_type: "int",
                hint: "Duration of the webinar, in minutes.",
            }
          - {
                label: "Preview text",
                name: "preview",
                widget: "string",
                hint: "1 or 2 sentences summarising the main purpose/content of the webinar.",
            }
          - {
                label: "Embed link",
                name: "embedLink",
                widget: "string",
                hint: "Open the webinar on YouTube, click 'Share' > 'embed', then copy the url in the 'src' attribute of the displayed embed link text. Refer to website documentation for screenshots and detailed instructions.",
            }
          - {
                label: "Thumbnail",
                name: "featureImage",
                widget: "image",
                hint: "Use the same thumbnail as YouTube.",
            }
          - {
                label: "Body",
                name: "body",
                widget: "markdown",
                hint: "Outline the webinar agenda in dot points.",
            }
